CREATE TABLE SQUADRA (IDSQUADRA BIGINT NOT NULL, FOTOSQUADRA BYTEA, NOMESQUADRA VARCHAR(255), PRIMARY KEY (IDSQUADRA))
CREATE TABLE MATCH (IDMATCH BIGINT NOT NULL, PRIMARY KEY (IDMATCH))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
